### ISSUE TITLE
Fetching AP Articles fails

### ISSUE THREAD

**Issue by shadowfacts** [hometown-fork/hometown#1183]
### Steps to reproduce the problem

Fetching AP `Article`s fails for multiple different reasons.

Fetching a text-only article (e.g., https://shadowfacts.net/2022/liveviewnative/) fails with
```
NameError (uninitialized constant ActivityPub::Activity::Create::Formatter
Did you mean?  Formatador):
app/lib/activitypub/activity/create.rb:426:in `text_from_content'
app/lib/activitypub/activity/create.rb:117:in `process_status_params'
app/lib/activitypub/activity/create.rb:80:in `process_status'
app/lib/activitypub/activity/create.rb:56:in `block in create_status'
app/lib/activitypub/activity.rb:169:in `block in lock_or_fail'
app/lib/activitypub/activity.rb:167:in `lock_or_fail'
app/lib/activitypub/activity/create.rb:50:in `create_status'
app/lib/activitypub/activity/create.rb:13:in `perform'
app/services/activitypub/fetch_remote_status_service.rb:42:in `call'
app/services/fetch_remote_status_service.rb:12:in `call'
app/services/resolve_url_service.rb:26:in `process_url'
app/services/resolve_url_service.rb:14:in `call'
app/services/search_service.rb:83:in `url_resource'
app/services/search_service.rb:16:in `block in call'
app/services/search_service.rb:12:in `call'
app/controllers/api/v2/search_controller.rb:23:in `search_results'
app/controllers/api/v2/search_controller.rb:12:in `index'
app/controllers/concerns/localized.rb:11:in `set_locale'
lib/mastodon/rack_middleware.rb:9:in `call'
```

Fetching an article with images (e.g., https://shadowfacts.net/2022/live-activities/) fails with:
```
NoMethodError (undefined method `file_remote_url=' for #<MediaAttachment id: 109197477688559207, status_id: nil, file_file_name: nil, file_content_type: nil, file_file_size: nil, file_updated_at: nil, remote_url: "/2022/live-activities/console.png", created_at: "2022-10-19 23:14:38.205830145 +0000", updated_at: "2022-10-19 23:14:38.205830145 +0000", shortcode: nil, type: "unknown", file_meta: nil, account_id: 109197448799935047, description: "com.apple.activitykit sessionkitd xpc Process is p...", scheduled_status_id: nil, blurhash: nil, processing: "complete", file_storage_schema_version: nil, thumbnail_file_name: nil, thumbnail_content_type: nil, thumbnail_file_size: nil, thumbnail_updated_at: nil, thumbnail_remote_url: nil>
Did you mean?  file_meta=):
app/lib/activitypub/activity/create.rb:174:in `block in process_inline_images'
app/lib/activitypub/activity/create.rb:167:in `each'
app/lib/activitypub/activity/create.rb:167:in `process_inline_images'
app/lib/activitypub/activity/create.rb:79:in `process_status'
app/lib/activitypub/activity/create.rb:56:in `block in create_status'
app/lib/activitypub/activity.rb:169:in `block in lock_or_fail'
app/lib/activitypub/activity.rb:167:in `lock_or_fail'
app/lib/activitypub/activity/create.rb:50:in `create_status'
app/lib/activitypub/activity/create.rb:13:in `perform'
app/services/activitypub/fetch_remote_status_service.rb:42:in `call'
app/services/fetch_remote_status_service.rb:12:in `call'
app/services/resolve_url_service.rb:26:in `process_url'
app/services/resolve_url_service.rb:14:in `call'
app/services/search_service.rb:83:in `url_resource'
app/services/search_service.rb:16:in `block in call'
app/services/search_service.rb:12:in `call'
app/controllers/api/v2/search_controller.rb:23:in `search_results'
app/controllers/api/v2/search_controller.rb:12:in `index'
app/controllers/concerns/localized.rb:11:in `set_locale'
lib/mastodon/rack_middleware.rb:9:in `call'
```

Both errors are reproducible by searching for the article URLs and looking at the Rails console.		

### Specifications

Only tested on the dev branch

**Comment by dariusk** [comment]
Confirming this was partially fixed by #1186 

![image](https://user-images.githubusercontent.com/266454/202611962-31d6479f-2c34-4280-9eec-0e484b399d6d.png)

But images still don't work if you try to fetch https://shadowfacts.net/2022/live-activities/. I'll fix this in an upcoming release. (The post renders, just the images don't show. Not ideal but at least it's not complete failure.)

**Comment by dariusk** [comment]
@shadowfacts So fetching images from a write.as blog works now -- there is a problem with the activitypub object I get when I do

```
curl -H "Accept: application/activity+json" https://shadowfacts.net/2022/live-activities/
```

There is an `<img src="/2022/live-activities/console.png">`, which you'll note is not a relative url and not a fully-specified url. I would recommend changing the `src` to the full `https://` url for the image.

So this seems to be a bug with your blog's activitypub code.

**Comment by dariusk** [comment]
This is fixed in the upcoming v1.0.8 release.

**Comment by shadowfacts** [comment]
I’ll change my blog to rewrite HTML in AP objects to have absolute URLs, but I don’t think the spec mandates it? It might be good to also change the ingest side to rewrite URLs to be absolute.

**Comment by dariusk** [comment]
@shadowfacts fair point. I'll see if I can finagle it for this release

**Comment by dariusk** [comment]
@shadowfacts I think this resolves it: https://github.com/hometown-fork/hometown/commit/9c4df2175352f21e77a5381234b38db37fab0f45

**Comment by shadowfacts** [comment]
👍 LGTM!
