### ISSUE TITLE
"Error: Missing access token"

### ISSUE THREAD

**Issue by yaxu** [hometown-fork/hometown#1349]
I've just gone through the upgrade process, but am getting "We're sorry, but something went wrong on our end."

In the logs I'm seeing a lot of 

```
Jul 04 21:25:41 social.toplap.org node[1164982]: ERR! 70097674-f054-422b-bcae-20266a0dc181 Error: Missing access token
```

Looking at my history I can see that I failed to put `SKIP_POST_DEPLOYMENT_MIGRATIONS=true` in front of the first db:migrate. Maybe that's the problem?

Any ideas about how to fix this much appreciated! I've tried re-running the migrate, and restarting everything, but no dice.

**Comment by yaxu** [comment]
It seems that's a red herring, the error is more likely:
`ActionView::Template::Error (Webpacker can't find locale/en-json.js in /home/mastodon/live/public/packs/manifest.json.`

**Comment by yaxu** [comment]
Aha, the precompile is failing:
```
mastodon@social:~/live$ RAILS_ENV=production bundle exec rails assets:clobber assets:precompile

I, [2024-07-04T21:46:26.183984 #1165860]  INFO -- : Removed /home/mastodon/live/public/assets
Removed webpack output path directory /home/mastodon/live/public/packs
I, [2024-07-04T21:46:26.612510 #1165860]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css
I, [2024-07-04T21:46:26.613301 #1165860]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css.gz
I, [2024-07-04T21:46:26.616252 #1165860]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css
I, [2024-07-04T21:46:26.616405 #1165860]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css.gz
I, [2024-07-04T21:46:26.619391 #1165860]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/favicon-db10337a56c45eb43c22ff5019546b520fa22c7281d4d385f235cbca67ed26bb.png
I, [2024-07-04T21:46:26.638198 #1165860]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-fc5c893e805df52338bef3bda5a5431f74f1401da68e4f0381ac9ecb7a801e1a.js
I, [2024-07-04T21:46:26.639195 #1165860]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-fc5c893e805df52338bef3bda5a5431f74f1401da68e4f0381ac9ecb7a801e1a.js.gz
I, [2024-07-04T21:46:26.644782 #1165860]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-29fa393e673685cdbf2fb2b637098a15b988605f46bfa962f6e0cb94d15bc567.css
I, [2024-07-04T21:46:26.645019 #1165860]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-29fa393e673685cdbf2fb2b637098a15b988605f46bfa962f6e0cb94d15bc567.css.gz
Compiling...
Compilation failed:
`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (/home/mastodon/live/node_modules/babel-plugin-lodash/node_modules/@babel/types/lib/validators/generated/index.js:2740:35)
    at PluginPass.Program (/home/mastodon/live/node_modules/babel-plugin-lodash/lib/index.js:102:44)
```

**Comment by yaxu** [comment]
I was just running out of memory during the precompile, apologies for the noise!
