### ISSUE TITLE
Articles with inline images not rendering correctly

### ISSUE THREAD

**Issue by dariusk** [hometown-fork/hometown#1359]
### Steps to reproduce the problem

1. In the web client, go to your search bar in `v4.2.0+hometown-1.1.1` and put in `https://kostyn.ca/fuck-sustainable-development-goals-have-yall-ever-heard-of-communism-reviewing-kohei-saitos-slow-down-the-degrowth-manifesto/`, click Search
2. You'll get a 500 error

### Expected behaviour

A search result appears

### Actual behaviour

A 500 error

### Detailed description

As initially reported in https://github.com/Automattic/wordpress-activitypub/issues/939

On a clean Hometown install when I put https://kostyn.ca/fuck-sustainable-development-goals-have-yall-ever-heard-of-communism-reviewing-kohei-saitos-slow-down-the-degrowth-manifesto/ into the search bar of the web client and search, I get a "500" error reported on the client side, and I get this in the logs:

```log
08:20:48 web.1     | Completed 500 Internal Server Error in 6606ms (ActiveRecord: 58.1ms | Allocations: 180111)
08:20:48 web.1     | 
08:20:48 web.1     | 
08:20:48 web.1     |   
08:20:48 web.1     | ArgumentError (wrong number of arguments (given 1, expected 0)):
08:20:48 web.1     |   
08:20:48 web.1     | app/lib/activitypub/activity/create.rb:139:in `initialize'
08:20:48 web.1     | app/lib/activitypub/activity/create.rb:167:in `new'
08:20:48 web.1     | app/lib/activitypub/activity/create.rb:167:in `process_inline_images'
08:20:48 web.1     | app/lib/activitypub/activity/create.rb:81:in `process_status'
08:20:48 web.1     | app/lib/activitypub/activity/create.rb:58:in `block in create_status'
08:20:48 web.1     | app/models/concerns/lockable.rb:12:in `block (2 levels) in with_redis_lock'
08:20:48 web.1     | app/models/concerns/lockable.rb:10:in `block in with_redis_lock'
08:20:48 web.1     | app/lib/redis_configuration.rb:10:in `with'
08:20:48 web.1     | app/models/concerns/redisable.rb:9:in `with_redis'
08:20:48 web.1     | app/models/concerns/lockable.rb:9:in `with_redis_lock'
08:20:48 web.1     | app/lib/activitypub/activity/create.rb:52:in `create_status'
08:20:48 web.1     | app/lib/activitypub/activity/create.rb:15:in `perform'
08:20:48 web.1     | app/services/activitypub/fetch_remote_status_service.rb:55:in `call'
08:20:48 web.1     | app/services/fetch_remote_status_service.rb:12:in `call'
08:20:48 web.1     | app/services/resolve_url_service.rb:28:in `process_url'
08:20:48 web.1     | app/services/resolve_url_service.rb:16:in `call'
08:20:48 web.1     | app/services/search_service.rb:77:in `url_resource'
08:20:48 web.1     | app/services/search_service.rb:19:in `block in call'
08:20:48 web.1     | app/services/search_service.rb:15:in `call'
08:20:48 web.1     | app/controllers/api/v2/search_controller.rb:33:in `search_results'
08:20:48 web.1     | app/controllers/api/v2/search_controller.rb:12:in `index'
08:20:48 web.1     | app/controllers/concerns/localized.rb:11:in `set_locale'
08:20:48 web.1     | lib/mastodon/rack_middleware.rb:9:in `call'
08:20:48 web.1     | lib/public_file_server_middleware.rb:18:in `call'
08:20:48 sidekiq.1 |   Account Load (0.3ms)  SELECT "accounts"."id", "account
```

The problem is that I'm passing the wrong number of arguments to `Ox` -- I think maybe I upgraded `Ox` for security reasons, their API surface changed, and now there's an issue with sending a parameter to the initializer.

### Specifications

`v4.2.0+hometown-1.1.1`

**Comment by nachtjasmin** [comment]
Can you reproduce this issue with `v4.5.11+hometown-1.2.1`? I tried to do it, but only got a 503 and a  

```
Storage server error: Net::ReadTimeout with #<TCPSocket:(closed)>
```

in the logs. To me it looks like it's at least trying to fetch the article and just runs into S3 timeouts afterwards, but no the same error that you've posted above.
