### ISSUE TITLE
Internal server error on posting due to activity_pub_type NoMethodError

### ISSUE THREAD

**Issue by simonlilburn** [hometown-fork/hometown#3]
### Expected behaviour
Post status (either publicly or privately, federated or local-only) from Hometown/Mastodon interface.

### Actual behaviour
Internal server error pop up appears in interface. Sidekiq job for status posting fails leaving stack trace. Partial stack trace from systemd:

```
Jul 08 11:54:42 sad-earth-prime bundle[1718]: 2019-07-08T11:54:42.475Z 1718 TID-owormn9r6 WARN: {"context":"Job raised exception","job":{"class":"DistributionWorker","args":[102405676040986322],"retry":true,"queue":"default","jid":"
c1c8052ef30731286e6c48fe","created_at":1562586609.5981352,"enqueued_at":1562586882.3866012,"error_message":"undefined method `activity_pub_type' for #<Status:0x00007fd11ab53c48>","error_class":"NoMethodError","failed_at":1562586609.
810376,"retry_count":3,"retried_at":1562586725.5024107},"jobstr":"{\"class\":\"DistributionWorker\",\"args\":[102405676040986322],\"retry\":true,\"queue\":\"default\",\"jid\":\"c1c8052ef30731286e6c48fe\",\"created_at\":1562586609.59
81352,\"enqueued_at\":1562586882.3866012,\"error_message\":\"undefined method `activity_pub_type' for #<Status:0x00007fd11ab53c48>\",\"error_class\":\"NoMethodError\",\"failed_at\":1562586609.810376,\"retry_count\":3,\"retried_at\":
1562586725.5024107}"}                                                                                                                                          
Jul 08 11:54:42 sad-earth-prime bundle[1718]: 2019-07-08T11:54:42.475Z 1718 TID-owormn9r6 WARN: NoMethodError: undefined method `activity_pub_type' for #<Status:0x00007fd1165be480>
Jul 08 11:54:42 sad-earth-prime bundle[1718]: 2019-07-08T11:54:42.476Z 1718 TID-owormn9r6 WARN: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.3/lib/active_model/attribute_methods.rb:430:in `method_missing'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/app/serializers/rest/status_serializer.rb:65:in `activity_pub_type'                
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:387:in `read_attribute_for_serialization'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer/field.rb:25:in `value'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:340:in `block in attributes'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:337:in `each'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:337:in `each_with_object'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:337:in `attributes'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:400:in `attributes_hash'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model/serializer.rb:368:in `serializable_hash'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/adapter/attributes.rb:9:in `serializable_hash'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/adapter/base.rb:61:in `as_json'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/serializable_resource.rb:10:in `as_json'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/logging.rb:71:in `block (3 levels) in notify'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/logging.rb:24:in `block (3 levels) in instrument_rendering'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/logging.rb:81:in `block in notify_render'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in `instrument'                                                             
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/logging.rb:80:in `notify_render'           
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/logging.rb:23:in `block (2 levels) in instrument_rendering'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/logging.rb:97:in `block in tag_logger'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/logging.rb:97:in `tag_logger'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/logging.rb:22:in `block in instrument_rendering'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `instance_exec'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:136:in `run_callbacks'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/active_model_serializers-0.10.9/lib/active_model_serializers/logging.rb:70:in `block (2 levels) in notify'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/app/lib/inline_renderer.rb:23:in `render'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/app/lib/inline_renderer.rb:27:in `render'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/app/services/fan_out_on_write_service.rb:67:in `render_anonymous_payload'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/app/services/fan_out_on_write_service.rb:9:in `call'
Jul 08 11:54:42 sad-earth-prime bundle[1718]: /home/mastodon/live/app/workers/distribution_worker.rb:9:in `block in perform'
[... snip ...]
```

**Comment by simonlilburn** [comment]
I've fixed it temporarily by checking out the commit b3e6597 (before **Adding full Article support**).

**Comment by dariusk** [comment]
Thanks for the report. I haven't written instructions for using Hometown yet.

Is this an attempt to migrate from Mastodon or to run Hometown on its own?

**Comment by dariusk** [comment]
I figured it out, I think. Please pull the `hometown-2.9.2` branch and try again, with a database migration.

**Comment by simonlilburn** [comment]
The update works perfectly! Thank you so much for looking at it :)

I installed Hometown just following the (non-Dockerised) Mastodon installation instructions, which worked well.
